version: '3'

services:
  rabbitmq:
    image: rabbitmq:management
    container_name: rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    volumes:
      - ./rabbitmq_data:/var/lib/rabbitmq
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASS}
    restart: always

  api:
    build:
      context: ./
    container_name: api
    ports:
      - "3000:3000" 
    depends_on:
      - rabbitmq
    environment:
      API_QUEUE: ${API_QUEUE}
      API_TESTE: ${API_TESTE}
      MONGO_URI: ${MONGO_URI}
    links:
      - rabbitmq
      - mongo
    restart: always

  mongo:
    image: mongo
    container_name: mongo
    ports:
      - "27017:27017"
    volumes:
      - ./mongo_data:/data/db
    restart: always
